server:
  port: ${PORT:8000}
spring:
  application:
    name: user-api
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    hostname: localhost:8761
    prefer-ip-address: true
